/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AutomatedPatternIdentification } from "./AutomatedPatternIdentification";
import { AutomatedPatternIdentificationCountArgs } from "./AutomatedPatternIdentificationCountArgs";
import { AutomatedPatternIdentificationFindManyArgs } from "./AutomatedPatternIdentificationFindManyArgs";
import { Query } from "../../query/base/Query";
import { AutomatedPatternIdentificationFindUniqueArgs } from "./AutomatedPatternIdentificationFindUniqueArgs";
import { DeleteAutomatedPatternIdentificationArgs } from "./DeleteAutomatedPatternIdentificationArgs";
import { AutomatedPatternIdentificationService } from "../automatedPatternIdentification.service";
@graphql.Resolver(() => AutomatedPatternIdentification)
export class AutomatedPatternIdentificationResolverBase {
  constructor(
    protected readonly service: AutomatedPatternIdentificationService
  ) {}

  async _automatedPatternIdentificationsMeta(
    @graphql.Args() args: AutomatedPatternIdentificationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AutomatedPatternIdentification])
  async automatedPatternIdentifications(
    @graphql.Args() args: AutomatedPatternIdentificationFindManyArgs
  ): Promise<AutomatedPatternIdentification[]> {
    return this.service.automatedPatternIdentifications(args);
  }

  @graphql.Query(() => AutomatedPatternIdentification, { nullable: true })
  async automatedPatternIdentification(
    @graphql.Args() args: AutomatedPatternIdentificationFindUniqueArgs
  ): Promise<AutomatedPatternIdentification | null> {
    const result = await this.service.automatedPatternIdentification(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AutomatedPatternIdentification)
  async deleteAutomatedPatternIdentification(
    @graphql.Args() args: DeleteAutomatedPatternIdentificationArgs
  ): Promise<AutomatedPatternIdentification | null> {
    try {
      return await this.service.deleteAutomatedPatternIdentification(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
